# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

users = User.create(
    [
        { name: 'User 1', email: 'email1@domain.org' },
        { name: 'User 2', email: 'email2@domain.org' },
        { name: 'User 3', email: 'email3@domain.org' },
        { name: 'User 4', email: 'email4@domain.org' },
        { name: 'User 5', email: 'email5@domain.org' },
        { name: 'User 6', email: 'email6@domain.org' },
        { name: 'User 7', email: 'email7@domain.org' },
        { name: 'User 8', email: 'email8@domain.org' },
        { name: 'User 9', email: 'email9@domain.org' },
        { name: 'User 10', email: 'email10@domain.org' },
        { name: 'User 11', email: 'email11@domain.org' },
        { name: 'User 12', email: 'email12@domain.org' },
        { name: 'User 13', email: 'email13@domain.org' },
        { name: 'User 14', email: 'email14@domain.org' },
        { name: 'User 15', email: 'email15@domain.org' },
        { name: 'User 16', email: 'email16@domain.org' },
        { name: 'User 17', email: 'email17@domain.org' },
        { name: 'User 18', email: 'email18@domain.org' },
        { name: 'User 19', email: 'email19@domain.org' },
        { name: 'User 20', email: 'email20@domain.org' },
        { name: 'User 21', email: 'email21@domain.org' },
        { name: 'User 22', email: 'email22@domain.org' },
        { name: 'User 23', email: 'email23@domain.org' },
        { name: 'User 24', email: 'email24@domain.org' },
        { name: 'User 25', email: 'email25@domain.org' },
        { name: 'User 26', email: 'email26@domain.org' },
        { name: 'User 27', email: 'email27@domain.org' },
        { name: 'User 28', email: 'email28@domain.org' },
        { name: 'User 29', email: 'email29@domain.org' },
        { name: 'User 30', email: 'email30@domain.org' },
        { name: 'User 31', email: 'email31@domain.org' },
        { name: 'User 32', email: 'email32@domain.org' },
        { name: 'User 33', email: 'email33@domain.org' },
        { name: 'User 34', email: 'email34@domain.org' },
        { name: 'User 35', email: 'email35@domain.org' },
        { name: 'User 36', email: 'email36@domain.org' },
        { name: 'User 37', email: 'email37@domain.org' },
        { name: 'User 38', email: 'email38@domain.org' },
        { name: 'User 39', email: 'email39@domain.org' },
        { name: 'User 40', email: 'email40@domain.org' },
        { name: 'User 41', email: 'email41@domain.org' },
        { name: 'User 42', email: 'email42@domain.org' },
        { name: 'User 43', email: 'email43@domain.org' },
        { name: 'User 44', email: 'email44@domain.org' },
        { name: 'User 45', email: 'email45@domain.org' },
        { name: 'User 46', email: 'email46@domain.org' },
        { name: 'User 47', email: 'email47@domain.org' },
        { name: 'User 48', email: 'email48@domain.org' },
        { name: 'User 49', email: 'email49@domain.org' },
        { name: 'User 50', email: 'email50@domain.org' },
        { name: 'User 51', email: 'email51@domain.org' },
        { name: 'User 52', email: 'email52@domain.org' },
        { name: 'User 53', email: 'email53@domain.org' },
        { name: 'User 54', email: 'email54@domain.org' },
        { name: 'User 55', email: 'email55@domain.org' },
        { name: 'User 56', email: 'email56@domain.org' },
        { name: 'User 57', email: 'email57@domain.org' },
        { name: 'User 58', email: 'email58@domain.org' },
        { name: 'User 59', email: 'email59@domain.org' },
        { name: 'User 60', email: 'email60@domain.org' },
        { name: 'User 61', email: 'email61@domain.org' },
        { name: 'User 62', email: 'email62@domain.org' },
        { name: 'User 63', email: 'email63@domain.org' },
        { name: 'User 64', email: 'email64@domain.org' },
        { name: 'User 65', email: 'email65@domain.org' },
        { name: 'User 66', email: 'email66@domain.org' },
        { name: 'User 67', email: 'email67@domain.org' },
        { name: 'User 68', email: 'email68@domain.org' },
        { name: 'User 69', email: 'email69@domain.org' },
        { name: 'User 70', email: 'email70@domain.org' },
        { name: 'User 71', email: 'email71@domain.org' },
        { name: 'User 72', email: 'email72@domain.org' },
        { name: 'User 73', email: 'email73@domain.org' },
        { name: 'User 74', email: 'email74@domain.org' },
        { name: 'User 75', email: 'email75@domain.org' },
        { name: 'User 76', email: 'email76@domain.org' },
        { name: 'User 77', email: 'email77@domain.org' },
        { name: 'User 78', email: 'email78@domain.org' },
        { name: 'User 79', email: 'email79@domain.org' },
        { name: 'User 80', email: 'email80@domain.org' },
        { name: 'User 81', email: 'email81@domain.org' },
        { name: 'User 82', email: 'email82@domain.org' },
        { name: 'User 83', email: 'email83@domain.org' },
        { name: 'User 84', email: 'email84@domain.org' },
        { name: 'User 85', email: 'email85@domain.org' },
        { name: 'User 86', email: 'email86@domain.org' },
        { name: 'User 87', email: 'email87@domain.org' },
        { name: 'User 88', email: 'email88@domain.org' },
        { name: 'User 89', email: 'email89@domain.org' },
        { name: 'User 90', email: 'email90@domain.org' },
        { name: 'User 91', email: 'email91@domain.org' },
        { name: 'User 92', email: 'email92@domain.org' },
        { name: 'User 93', email: 'email93@domain.org' },
        { name: 'User 94', email: 'email94@domain.org' },
        { name: 'User 95', email: 'email95@domain.org' },
        { name: 'User 96', email: 'email96@domain.org' },
        { name: 'User 97', email: 'email97@domain.org' },
        { name: 'User 98', email: 'email98@domain.org' },
        { name: 'User 99', email: 'email99@domain.org' },
        { name: 'User 100', email: 'email100@domain.org' }
    ]
)